---
- name: Install git
  ansible.builtin.apt:
    name:
      - git
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Clone static website
  ansible.builtin.git:
    repo: https://github.com/RossGammon/html-website.git
    dest: /var/www/html
    version: main
